### PR TITLE
GET MANY REFERENCE

### PR DESCRIPTION
**Pull request by fonzarely**
This makes the reference id to be passed to the api as parameter.

### CODE REVIEW

**Comment by fonzarely** [comment]
I do not see the CI telling me if the tests are passing. Is it still active ? Test are passing on my local branch.

**Comment by fonzarely** [comment]
I also see that this PR contains 3 commits instead of 1 commit of my changes. You may squash and merge to have only one on master.

**Comment by josx** [comment]
my bad, i have turn on Build forked pull requests on circleci.

**Comment by josx** [comment]
@fonzarely please can you squash the 3 commits in this PR, so i just click on "Merge pull request"

**Comment by fonzarely** [comment]
I dont think I can do it. I may have to reset my git to do so.
You should have this button in place of merge button.
image
Let me know.

**Comment by fonzarely** [comment]
Sorry for this.

**Comment by josx** [comment]
no problem! thanks you for the PR

**Pull request merged**
