### PR TITLE
Add circle ci

### PR DESCRIPTION
**Pull request by fonzarely**
This will add circle CI configuration tu run the tests and build.
This is very useful to make sure a PR pass all tests and not having to run them manually.

I added yarn to speed up the process, yarn keep a packages cache.
This mean any one would have to use yarn when adding new libs to update yarn.lock file.

To add Circle CI to this projet : 
1. Sign up to https://circleci.com/
2. Go https://circleci.com/dashboard
3. Go to project (square icon on left menu), select your account, then add project.

This should add the circle ci web hook this the git project. On next push you will see CI running tests and build.

PS: Add circle CI before merging this branch so we could make sure the configuration works ;)

### CODE REVIEW

**Comment by fonzarely** [comment]
Did the circle CI run the tests ? I do not see the hook on my other PR.

**Comment by josx** [comment]
Yes, take a look https://circleci.com/gh/josx/aor-feathers-client/2

**Comment by fonzarely** [comment]
Excellent.

**Comment by fonzarely** [comment]
The issue is that I do not see the status on https://github.com/josx/aor-feathers-client/pull/21
. So as long as you see them it's better than nothing.

**Comment by josx** [comment]
mmm Now i have updated circle conf to "Only build pull requests"
https://discuss.circleci.com/t/pull-requests-not-triggering-build/1213/16

**Pull request merged**
